from yacs.config import CfgNode as CN

_C = CN()

# Model

_C.MODEL = CN()
_C.MODEL.NAME = ""
_C.MODEL.DEVICE = "cuda"
_C.MODEL.PRETRAINED = ""

# EfficientNet Parameters
_C.MODEL.DROPOUT_RATE = 0.2
_C.MODEL.DROPCONNECT_RATE = 0.2
_C.MODEL.CHANNEL_MULTIPLIER = 1.0
_C.MODEL.DEPTH_MULTIPLIER = 1.0

# ResNet Parameters
_C.MODEL.RESNET_BLOCK = "Basic"
_C.MODEL.RESNET_LAYERS = (2, 2, 2, 2)

# VGG Parameters
_C.MODEL.VGG_NUM = 16


# Solver

_C.SOLVER = CN()
_C.SOLVER.BASE_LR = 0.1
_C.SOLVER.BATCHSIZE = 128
_C.SOLVER.NUM_WORKERS = 0
_C.SOLVER.MOMENTUM = 0.9
_C.SOLVER.WEIGHT_DECAY = 0.0005
_C.SOLVER.MILESTONES = (150, 250)
_C.SOLVER.GAMMA = 0.1
_C.SOLVER.END_EPOCH = 350

# Data
_C.DATA = CN()
_C.DATA.IMG_SIZE = 32
_C.DATA.RANDOMCROP = True
_C.DATA.LRFLIP = True
_C.DATA.NORMALIZE_MEAN = (0.4914, 0.4822, 0.4465)
_C.DATA.NORMALIZE_STD = (0.2023, 0.1994, 0.2010)

# Test
_C.TEST = CN()
_C.TEST.BATCHSIZE = 100
_C.TEST.IMG_SIZE = 32