# Model

MODEL:
  NAME: ""
  DEVICE: "cuda"
  PRETRAINED: ""
  # ResNet Parameters
  RESNET_BLOCK: "Basic"
  RESNET_LAYERS: [2, 2, 2, 2]
  # VGG Parameters
  VGG_NUM: 16


# Solver

SOLVER:
  BASE_LR: 0.1
  BATCHSIZE: 128
  NUM_WORKERS: 0
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  MILESTONES: [150, 250]
  GAMMA: 0.1
  END_EPOCH: 350

# Data
DATA:
  IMG_SIZE: 32
  RANDOMCROP: True
  LRFLIP: True
  NORMALIZE_MEAN: [0.4914, 0.4822, 0.4465]
  NORMALIZE_STD: [0.2023, 0.1994, 0.2010]

TEST:
  BATCHSIZE: 100
  IMG_SIZE: 32
