# Fine-tuning imagenet-pretrained model

MODEL:
  NAME: "EfficientNet"
  PRETRAINED: "EfficientNetB0"
  DROPOUT_RATE: 0.2
  DROPCONNECT_RATE: 0.2
  CHANNEL_MULTIPLIER: 1.0
  DEPTH_MULTIPLIER: 1.0
DATA:
  IMG_SIZE: 224
  RANDOMCROP: True
SOLVER:
  BASE_LR: 0.01
  BATCHSIZE: 48
  MILESTONES: (20, 30)
  END_EPOCH : 35
  WEIGHT_DECAY: 0.0001
TEST:
  BATCHSIZE: 50
  IMG_SIZE: 224