# Fine-tuning imagenet-pretrained model

MODEL:
  NAME: "EfficientNet"
  PRETRAINED: "EfficientNetB6"
  DROPOUT_RATE: 0.5
  DROPCONNECT_RATE: 0.2
  CHANNEL_MULTIPLIER: 1.8
  DEPTH_MULTIPLIER: 2.6
DATA:
  IMG_SIZE: 224
  RANDOMCROP: True
SOLVER:
  BASE_LR: 0.01
  BATCHSIZE: 8
  MILESTONES: (20, 30)
  END_EPOCH : 35
  WEIGHT_DECAY: 0.0001
TEST:
  BATCHSIZE: 4
  IMG_SIZE: 528